### ISSUE TITLE
Thread timeout | "Þeistareykjarbunga bug"

### ISSUE THREAD

**Issue by lahire** [lahire/wiki-imagefinder#8]
Después de un cierto tiempo (como 40 minutos) el programa se detiene, deja de consumir CPU pero mantiene memoria. Se queda en el  factoring(q.get()) y para. Recién alrededor de 3k resultados de imágenes y para. 

Se está probando meter un timeout para ver si no es algo de hilos

**Comment by lahire** [comment]
Potencial fix:
al momento de hacer factorin(q.get()) con q.get() siendo la page de Þeistareykjarbunga se colgaba todo mal
haciendo una prueba breve asignando el get a una varialble parece que pasó. (p = q.get() y luego factorin(p))

veremos que pasa, está corriendo en la nube

**Comment by dennistobar** [comment]
Tras probar, creo que el problema viene derivado de se asigna más rápido en la cola de lo que se procesa de la misma, por lo cual genera ese problema. Probé con `q.qsize()` tras el `q.task_done()` y quedan elementos en la cola de tareas, por lo cual creo que la paralelización es efectiva al momento de procesar los recursos, pero la asignación en cola -y por tanto el uso de memoria- va a ser alto sin dudas.

**Comment by lahire** [comment]
Si. corriéndolo sin jsub el consumo se va al demonio. y viendo lo de imprimir el qsize el en bucle se puede ver que termina. 
Pensé en ponerle un límite a la cola, al momento de la declaración, pero no hubo caso :(

**Comment by lahire** [comment]
corriendo con jsub
Traceback (most recent call last):                                                                    
  File "/data/project/shared/pywikipedia/core/pywikibot/data/api.py", line 1966, in submit            
  File "/data/project/shared/pywikipedia/core/pywikibot/tools/__init__.py", line 1426, in wrapper     
  File "/data/project/shared/pywikipedia/core/pywikibot/comms/http.py", line 319, in request          
  File "/data/project/shared/pywikipedia/core/pywikibot/comms/threadedhttp.py", line 200, in text     
  File "/data/project/shared/pywikipedia/core/pywikibot/comms/threadedhttp.py", line 166, in encoding 
MemoryError           

During handling of the above exception, another exception occurred:                                               
                                                                                                                  
Traceback (most recent call last):                                                                                
  File "/mnt/nfs/labstore-secondary-tools-project/lahitools/wiki-imagefinder/main.py", line 168, in <module>      
  File "/mnt/nfs/labstore-secondary-tools-project/lahitools/wiki-imagefinder/main.py", line 157, in main          
  File "/data/project/shared/pywikipedia/core/pywikibot/pagegenerators.py", line 2069, in PreloadingGenerator     
  File "/data/project/shared/pywikipedia/core/pywikibot/site.py", line 3365, in preloadpages                      
  File "/data/project/shared/pywikipedia/core/pywikibot/data/api.py", line 2835, in __iter__                      
  File "/data/project/shared/pywikipedia/core/pywikibot/data/api.py", line 1988, in submit                        
  File "/usr/lib/python3.4/traceback.py", line 256, in format_exc                                                 
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))                                   
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception                                           
    return list(_format_exception_iter(etype, value, tb, limit, chain))                                           
  File "/usr/lib/python3.4/traceback.py", line 153, in _format_exception_iter                                     
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))                                               
  File "/usr/lib/python3.4/traceback.py", line 18, in _format_list_iter                                           
    for filename, lineno, name, line in extracted_list:                                                           
  File "/usr/lib/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter                                   
    line = linecache.getline(filename, lineno, f.f_globals)                                                       
  File "/usr/lib/python3.4/linecache.py", line 15, in getline                                                     
    lines = getlines(filename, module_globals)                                                                    
  File "/usr/lib/python3.4/linecache.py", line 41, in getlines                                                    
    return updatecache(filename, module_globals)                                                                  
  File "/usr/lib/python3.4/linecache.py", line 126, in updatecache                                                
    with tokenize.open(fullname) as fp:                                                                           
  File "/usr/lib/python3.4/tokenize.py", line 438, in open                                                        
    buffer = _builtin_open(filename, 'rb')                                                                        
MemoryError                                                                                                       
Error in atexit._run_exitfuncs:                                                                                   
Traceback (most recent call last):                                                                                
  File "/data/project/shared/pywikipedia/core/pywikibot/__init__.py", line 1393, in _flush                        
  File "/data/project/shared/pywikipedia/core/pywikibot/throttle.py", line 203, in drop                           
MemoryError                                                                                                       
CRITICAL: Closing network session.

**Comment by lahire** [comment]
out:
Size: 12225            
Size: 12224            
Size: 12223            
Size: 12222            
Size: 12221            
Size: 12220            
<class 'MemoryError'>

**Comment by dennistobar** [comment]
Ok, nos quedamos sin memoria: almacenar en la cola es más rápido que el procesamiento... quizás sería entrar en un ciclo de limitar la cola y no añadir más elementos hasta que la cola tenga espacio de x elementos tras procesamiento, aunque no se me ocurre mucho

**Comment by lahire** [comment]
Probando correr el programa con una queua con tamaño limitado

**Comment by lahire** [comment]
Posible fix en commit 5b31130

**Comment by dennistobar** [comment]
Me parece que podría funcionar bien. Yo lo dejaría configurado en una cola igual al doble de la cantidad de elementos que podemos obtener desde el servidor (aka: bot = 200, no-bot = 50, por tanto, maxsize=400 o 100). 1000 igual es algo exagerado :smile:

**Comment by lahire** [comment]
Bueno, ahora el proceso está corriendo por cron y todavía no terminó, hace mas o menos una hora que corre y no termina

**Comment by dennistobar** [comment]
Al menos terminó una vez en línea (21.18 UTC)....

**Comment by lahire** [comment]
quizas nada que ver, pero corriendo una vez me tiró:
un http 503
set gtllimit 250 (?)

**Comment by lahire** [comment]
Bueno, corrí de vuelta el script en la nuve sin pasar por jsub y anduvo perfecto. El tema es que sigue estando la tarea abierta en qstat, voy a intentar matarla a mano para evitar que se solapen

**Comment by lahire** [comment]
Bueno, parece que anda. Quise subir la cantidad de threads pero no le gustó al jsub. El tiempo dirá. quisiera una configrmación más para cerrar este issue

**Comment by lahire** [comment]
Bueno, el script se corrió con jsub. Voy a esperar a que lo corra solo (por tarea croneada) y vemos que pasa. vamos que ya sale (?)

**Comment by dennistobar** [comment]
Bien :+1:... aún quedan algunas cosas más, pero al menos ya avanzamos

**Comment by dennistobar** [comment]
Anoche corrió por 73 minutos, al parecer vamos mejorando :)

**Comment by lahire** [comment]
Bueno, le encontramos la vuelta.
